+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Dec  6 07:50:55 2022 - INFO  - Start to run test.
+ echo openEuler
+ chmod 777 /tmp/file_push
+ expect
spawn scp -p /tmp/file_push @:/tmp
ssh: Could not resolve hostname : Name or service not known
scp: Connection closed
expect: spawn id exp3 not open
    while executing
"expect {
            "password" {
                send "\r"
            }
        }"
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssh_scp_p.sh line 38'
+ message='oe_test_openssh_scp_p.sh line 38'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssh_scp_p.sh line 38'
Tue Dec  6 07:50:57 2022 - ERROR - oe_test_openssh_scp_p.sh line 38
+ return 0
+ SSH_CMD '
    grep openEuler /tmp/file_push 
    ls -l /tmp/file_push | grep '\''rwxrwxrwx'\''
    ' '' '' ''
+ cmd='
    grep openEuler /tmp/file_push 
    ls -l /tmp/file_push | grep '\''rwxrwxrwx'\''
    '
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c '
    grep openEuler /tmp/file_push 
    ls -l /tmp/file_push | grep '\''rwxrwxrwx'\''
    ' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Dec  6 07:50:57 2022 - ERROR - Failed in remote CMD operation:1
+ return 1
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssh_scp_p.sh line 43'
+ message='oe_test_openssh_scp_p.sh line 43'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssh_scp_p.sh line 43'
Tue Dec  6 07:50:58 2022 - ERROR - oe_test_openssh_scp_p.sh line 43
+ return 0
+ expect
spawn scp -p @:/tmp/file_push /tmp/file_pull
ssh: Could not resolve hostname : Name or service not known
scp: Connection closed
expect: spawn id exp3 not open
    while executing
"expect {
            "password" {
                send "\r"
            }
        }"
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssh_scp_p.sh line 58'
+ message='oe_test_openssh_scp_p.sh line 58'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssh_scp_p.sh line 58'
Tue Dec  6 07:50:59 2022 - ERROR - oe_test_openssh_scp_p.sh line 58
+ return 0
+ ls -l /tmp/file_pull
+ grep rwxrwxrwx
ls: cannot access '/tmp/file_pull': No such file or directory
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssh_scp_p.sh line 60'
+ message='oe_test_openssh_scp_p.sh line 60'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssh_scp_p.sh line 60'
Tue Dec  6 07:51:00 2022 - ERROR - oe_test_openssh_scp_p.sh line 60
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Dec  6 07:51:01 2022 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 4
+ test 4 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Dec  6 07:51:02 2022 - ERROR - failed to execute the case.
+ exit 4
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Dec  6 07:51:02 2022 - INFO  - Start to restore the test environment.
+ rm -rf /tmp/file_push
+ SSH_CMD 'rm -rf /tmp/file_*' '' '' ''
+ cmd='rm -rf /tmp/file_*'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'rm -rf /tmp/file_*' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Dec  6 07:51:03 2022 - ERROR - Failed in remote CMD operation:1
+ return 1
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Dec  6 07:51:04 2022 - INFO  - End to restore the test environment.
