+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Wed Nov 22 04:59:25 2023 - INFO  - Start environment preparation.
+ dd if=/dev/zero of=test.tar bs=4M count=10
10+0 records in
10+0 records out
41943040 bytes (42 MB, 40 MiB) copied, 0.43051 s, 97.4 MB/s
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Wed Nov 22 04:59:26 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Wed Nov 22 04:59:26 2023 - INFO  - Start testing...
+ pigz test.tar
oe_test_pigz.sh: line 30: pigz: command not found
+ ls test.tar.gz
ls: cannot access 'test.tar.gz': No such file or directory
+ CHECK_RESULT 2 0 0 'pgiz compression failure'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='pgiz compression failure'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'pgiz compression failure'
+ LOG_ERROR 'pgiz compression failure'
+ message='pgiz compression failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'pgiz compression failure'
Wed Nov 22 04:59:27 2023 - ERROR - pgiz compression failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pigz.sh line 32'
+ message='oe_test_pigz.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pigz.sh line 32'
Wed Nov 22 04:59:27 2023 - ERROR - oe_test_pigz.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ pid=625
+ pigz -d -p 8 test.tar.gz
oe_test_pigz.sh: line 33: pigz: command not found
++ grep Threads
++ awk '{print $NF}'
++ cat /proc/625/status
cat: /proc/625/status: No such file or directory
+ number=
+ '[' -le 8 ']'
oe_test_pigz.sh: line 36: [: -le: unary operator expected
+ CHECK_RESULT 2 0 0 'The number of threads displayed is greater than the set number of threads 8'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='The number of threads displayed is greater than the set number of threads 8'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'The number of threads displayed is greater than the set number of threads 8'
+ LOG_ERROR 'The number of threads displayed is greater than the set number of threads 8'
+ message='The number of threads displayed is greater than the set number of threads 8'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The number of threads displayed is greater than the set number of threads 8'
Wed Nov 22 04:59:28 2023 - ERROR - The number of threads displayed is greater than the set number of threads 8
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pigz.sh line 37'
+ message='oe_test_pigz.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pigz.sh line 37'
Wed Nov 22 04:59:28 2023 - ERROR - oe_test_pigz.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ tar -cvf - /var/log
+ pigz -k
oe_test_pigz.sh: line 38: pigz: command not found
tar: Removing leading `/' from member names
/var/log/
/var/log/README
/var/log/dnf.librepo.log
+ CHECK_RESULT 127 0 0 'pgiz cannot be used with tar'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='pgiz cannot be used with tar'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'pgiz cannot be used with tar'
+ LOG_ERROR 'pgiz cannot be used with tar'
+ message='pgiz cannot be used with tar'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'pgiz cannot be used with tar'
Wed Nov 22 04:59:29 2023 - ERROR - pgiz cannot be used with tar
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pigz.sh line 39'
+ message='oe_test_pigz.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pigz.sh line 39'
Wed Nov 22 04:59:29 2023 - ERROR - oe_test_pigz.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Wed Nov 22 04:59:30 2023 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 3
+ test 3 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Nov 22 04:59:30 2023 - ERROR - failed to execute the case.
+ exit 3
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Wed Nov 22 04:59:31 2023 - INFO  - start environment cleanup.
+ rm -rf test.tar logs.tar.gz
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Wed Nov 22 04:59:32 2023 - INFO  - Finish environment cleanup!
