+ source ../common/common.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n function ']'
+ config_params
+ LOG_INFO 'Start to config params of the case.'
+ message='Start to config params of the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to config params of the case.'
Tue Nov 21 17:45:04 2023 - INFO  - Start to config params of the case.
++ mktemp -d -t nototools.XXXXXXXXXXXX
+ TMP_DIR=/tmp/nototools.RTTFgYda6aLz
+ LOG_INFO 'End to config params of the case.'
+ message='End to config params of the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to config params of the case.'
Tue Nov 21 17:45:05 2023 - INFO  - End to config params of the case.
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Tue Nov 21 17:45:05 2023 - INFO  - Start to prepare the test environment.
+ common_pre
+ pip install -r ../common/requirements.txt
+ DNF_INSTALL 'nototools harfbuzz-devel cpio pango python3-gobject python3-cairo'
+ pkgs='nototools harfbuzz-devel cpio pango python3-gobject python3-cairo'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'nototools harfbuzz-devel cpio pango python3-gobject python3-cairo' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpdl5hj3nq
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpdl5hj3nq
+ notoconfig_pre
++ mktemp -d -t nototools.SRC.XXXXXXXXXXXX
+ TMP_SRCDIR=/tmp/nototools.SRC.4SIV6lHGY4y1
+ yumdownloader --source nototools --destdir /tmp/nototools.SRC.4SIV6lHGY4y1
No package nototools-0.2.17-1.oe2303.src available.
Exiting due to strict setting.
Error: No package nototools-0.2.17-1.oe2303.src available.
+ rpm2cpio '/tmp/nototools.SRC.4SIV6lHGY4y1/*.rpm'
+ cpio -div -D /tmp/nototools.SRC.4SIV6lHGY4y1
rpm2cpio: /tmp/nototools.SRC.4SIV6lHGY4y1/*.rpm: No such file or directory
+ tar -zxf '/tmp/nototools.SRC.4SIV6lHGY4y1/*.tar.gz' --strip-components 1 --directory /tmp/nototools.SRC.4SIV6lHGY4y1
tar (child): /tmp/nototools.SRC.4SIV6lHGY4y1/*.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
+ echo noto_tools=/tmp/nototools.SRC.4SIV6lHGY4y1
+ for src in "fonts" "cjk" "emoji"
+ echo noto_fonts=/tmp/nototools.SRC.4SIV6lHGY4y1/noto-fonts
+ for src in "fonts" "cjk" "emoji"
+ echo noto_cjk=/tmp/nototools.SRC.4SIV6lHGY4y1/noto-cjk
+ for src in "fonts" "cjk" "emoji"
+ echo noto_emoji=/tmp/nototools.SRC.4SIV6lHGY4y1/noto-emoji
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Tue Nov 21 17:51:46 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Nov 21 17:51:47 2023 - INFO  - Start to run test.
+ autofix_for_release.py -h
+ grep -q usage
Traceback (most recent call last):
  File "/usr/bin/autofix_for_release.py", line 398, in <module>
    main()
  File "/usr/bin/autofix_for_release.py", line 356, in main
    default_src_root = notoconfig.values.get("alpha")
AttributeError: module 'nototools.notoconfig' has no attribute 'values'. Did you mean: '_values'?
+ CHECK_RESULT 1 0 0 'option: -h error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: -h error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: -h error'
+ LOG_ERROR 'option: -h error'
+ message='option: -h error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: -h error'
Tue Nov 21 17:52:13 2023 - ERROR - option: -h error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_autofix_for_release.sh line 47'
+ message='oe_test_nototools_base_autofix_for_release.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_autofix_for_release.sh line 47'
Tue Nov 21 17:52:13 2023 - ERROR - oe_test_nototools_base_autofix_for_release.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ autofix_for_release.py --help
+ grep -q usage
Traceback (most recent call last):
  File "/usr/bin/autofix_for_release.py", line 398, in <module>
    main()
  File "/usr/bin/autofix_for_release.py", line 356, in main
    default_src_root = notoconfig.values.get("alpha")
AttributeError: module 'nototools.notoconfig' has no attribute 'values'. Did you mean: '_values'?
+ CHECK_RESULT 1 0 0 'option: --help error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --help error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --help error'
+ LOG_ERROR 'option: --help error'
+ message='option: --help error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --help error'
Tue Nov 21 17:52:39 2023 - ERROR - option: --help error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_autofix_for_release.sh line 49'
+ message='oe_test_nototools_base_autofix_for_release.sh line 49'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_autofix_for_release.sh line 49'
Tue Nov 21 17:52:39 2023 - ERROR - oe_test_nototools_base_autofix_for_release.sh line 49
+ '[' 0 -eq 1 ']'
+ return 0
+ autofix_for_release.py --src_root ./ --dst_root /tmp/nototools.RTTFgYda6aLz NotoSans-Regular.ttf
Traceback (most recent call last):
  File "/usr/bin/autofix_for_release.py", line 398, in <module>
    main()
  File "/usr/bin/autofix_for_release.py", line 356, in main
    default_src_root = notoconfig.values.get("alpha")
AttributeError: module 'nototools.notoconfig' has no attribute 'values'. Did you mean: '_values'?
+ CHECK_RESULT 1 0 0 'option: --src_root --dst_root error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --src_root --dst_root error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --src_root --dst_root error'
+ LOG_ERROR 'option: --src_root --dst_root error'
+ message='option: --src_root --dst_root error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --src_root --dst_root error'
Tue Nov 21 17:53:05 2023 - ERROR - option: --src_root --dst_root error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_autofix_for_release.sh line 55'
+ message='oe_test_nototools_base_autofix_for_release.sh line 55'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_autofix_for_release.sh line 55'
Tue Nov 21 17:53:06 2023 - ERROR - oe_test_nototools_base_autofix_for_release.sh line 55
+ '[' 0 -eq 1 ']'
+ return 0
+ autofix_for_release.py --src_root ./ --dst_root /tmp/nototools.RTTFgYda6aLz --save_unmodified NotoSans-Regular.ttf
Traceback (most recent call last):
  File "/usr/bin/autofix_for_release.py", line 398, in <module>
    main()
  File "/usr/bin/autofix_for_release.py", line 356, in main
    default_src_root = notoconfig.values.get("alpha")
AttributeError: module 'nototools.notoconfig' has no attribute 'values'. Did you mean: '_values'?
+ CHECK_RESULT 1 0 0 'option: --src_root --dst_root --save_unmodified error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --src_root --dst_root --save_unmodified error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --src_root --dst_root --save_unmodified error'
+ LOG_ERROR 'option: --src_root --dst_root --save_unmodified error'
+ message='option: --src_root --dst_root --save_unmodified error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --src_root --dst_root --save_unmodified error'
Tue Nov 21 17:53:31 2023 - ERROR - option: --src_root --dst_root --save_unmodified error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_autofix_for_release.sh line 60'
+ message='oe_test_nototools_base_autofix_for_release.sh line 60'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_autofix_for_release.sh line 60'
Tue Nov 21 17:53:31 2023 - ERROR - oe_test_nototools_base_autofix_for_release.sh line 60
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Nov 21 17:53:32 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 4
+ test 4 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Nov 21 17:53:33 2023 - ERROR - failed to execute the case.
+ exit 4
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Nov 21 17:53:33 2023 - INFO  - Start to restore the test environment.
+ rm -rf /tmp/nototools.RTTFgYda6aLz
+ common_post
+ rm -rf /tmp/nototools.SRC.4SIV6lHGY4y1 /root/.notoconfig
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpdl5hj3nq ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpdl5hj3nq
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Nov 21 17:54:41 2023 - INFO  - End to restore the test environment.
