+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n function ']'
+ config_params
+ LOG_INFO 'Start loading data!'
+ message='Start loading data!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start loading data!'
Tue Nov 21 04:02:19 2023 - INFO  - Start loading data!
++ SSH_CMD 'ip route | grep 192.168.114.7 | awk '\''{print$3}'\''' 192.168.114.7 'openEuler12#$' root
++ tail -n 1
++ cmd='ip route | grep 192.168.114.7 | awk '\''{print$3}'\'''
++ tr '\r' ' '
++ remoteip=192.168.114.7
++ remotepasswd='openEuler12#$'
++ remoteuser=root
++ timeout=300
++ connport=22
++ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'ip route | grep 192.168.114.7 | awk '\''{print$3}'\''' -i 192.168.114.7 -u root -p 'openEuler12#$' -t 300 -o 22
Tue Nov 21 04:02:22 2023 - ERROR - connection to 192.168.114.7 failed.
++ ret=101
++ test 101 -ne 0
++ LOG_ERROR 'Failed in remote CMD operation:101'
++ message='Failed in remote CMD operation:101'
++ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:101'
Tue Nov 21 04:02:23 2023 - ERROR - Failed in remote CMD operation:101
++ return 101
+ remote_eth1='1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms'
+ LOG_INFO 'Loading data is complete!'
+ message='Loading data is complete!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Loading data is complete!'
Tue Nov 21 04:02:23 2023 - INFO  - Loading data is complete!
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Tue Nov 21 04:02:24 2023 - INFO  - Start to prepare the test environment.
+ SSH_CMD 'yum install -y vsftpd;systemctl start vsftpd;chmod -R 777 /var/ftp/pub;
    cd /var/ftp/pub;touch download_file1.txt download_file2.txt;
    cp /etc/vsftpd/ftpusers /etc/vsftpd/ftpusers.bak;sed -i /root/d /etc/vsftpd/ftpusers;echo \"#root\" >> /etc/vsftpd/ftpusers;
    cp /etc/vsftpd/user_list /etc/vsftpd/user_list.bak;sed -i /root/d /etc/vsftpd/user_list;echo \"#root\" >> /etc/vsftpd/user_list;
    systemctl restart vsftpd;' 192.168.114.7 'openEuler12#$' root
+ cmd='yum install -y vsftpd;systemctl start vsftpd;chmod -R 777 /var/ftp/pub;
    cd /var/ftp/pub;touch download_file1.txt download_file2.txt;
    cp /etc/vsftpd/ftpusers /etc/vsftpd/ftpusers.bak;sed -i /root/d /etc/vsftpd/ftpusers;echo \"#root\" >> /etc/vsftpd/ftpusers;
    cp /etc/vsftpd/user_list /etc/vsftpd/user_list.bak;sed -i /root/d /etc/vsftpd/user_list;echo \"#root\" >> /etc/vsftpd/user_list;
    systemctl restart vsftpd;'
+ remoteip=192.168.114.7
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'yum install -y vsftpd;systemctl start vsftpd;chmod -R 777 /var/ftp/pub;
    cd /var/ftp/pub;touch download_file1.txt download_file2.txt;
    cp /etc/vsftpd/ftpusers /etc/vsftpd/ftpusers.bak;sed -i /root/d /etc/vsftpd/ftpusers;echo \"#root\" >> /etc/vsftpd/ftpusers;
    cp /etc/vsftpd/user_list /etc/vsftpd/user_list.bak;sed -i /root/d /etc/vsftpd/user_list;echo \"#root\" >> /etc/vsftpd/user_list;
    systemctl restart vsftpd;' -i 192.168.114.7 -u root -p 'openEuler12#$' -t 300 -o 22
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
Tue Nov 21 04:02:27 2023 - ERROR - connection to 192.168.114.7 failed.
+ ret=101
+ test 101 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:101'
+ message='Failed in remote CMD operation:101'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:101'
Tue Nov 21 04:02:28 2023 - ERROR - Failed in remote CMD operation:101
+ return 101
+ DNF_INSTALL ftp
+ pkgs=ftp
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs ftp --node 1 --tempfile ''
+ tmpfile2=/tmp/tmp_mte4l2x
+ '[' -z '' ']'
+ tmpfile=/tmp/tmp_mte4l2x
+ setsebool -P ftpd_full_access=on
oe_test_server_vsftpd_NKdelay.sh: line 35: setsebool: command not found
+ SSH_CMD 'setsebool -P ftpd_full_access=on' 192.168.114.7 'openEuler12#$' root
+ cmd='setsebool -P ftpd_full_access=on'
+ remoteip=192.168.114.7
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'setsebool -P ftpd_full_access=on' -i 192.168.114.7 -u root -p 'openEuler12#$' -t 300 -o 22
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
Tue Nov 21 04:02:58 2023 - ERROR - connection to 192.168.114.7 failed.
+ ret=101
+ test 101 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:101'
+ message='Failed in remote CMD operation:101'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:101'
Tue Nov 21 04:02:59 2023 - ERROR - Failed in remote CMD operation:101
+ return 101
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Tue Nov 21 04:02:59 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Nov 21 04:03:00 2023 - INFO  - Start to run test.
+ SSH_CMD 'tc qdisc add dev 1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms root netem loss 20%' 192.168.114.7 'openEuler12#$' root
+ cmd='tc qdisc add dev 1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms root netem loss 20%'
+ remoteip=192.168.114.7
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'tc qdisc add dev 1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms root netem loss 20%' -i 192.168.114.7 -u root -p 'openEuler12#$' -t 300 -o 22
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
Tue Nov 21 04:03:03 2023 - ERROR - connection to 192.168.114.7 failed.
+ ret=101
+ test 101 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:101'
+ message='Failed in remote CMD operation:101'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:101'
Tue Nov 21 04:03:04 2023 - ERROR - Failed in remote CMD operation:101
+ return 101
+ ftp -n 192.168.114.7
ftp: connect: No route to host
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep -iE 'error|fail' log
+ CHECK_RESULT 1 1
+ actual_result=1
+ expect_result=1
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 1x
+ return 0
+ find download_file1.txt
find: ‘download_file1.txt’: No such file or directory
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_server_vsftpd_NKdelay.sh line 53'
+ message='oe_test_server_vsftpd_NKdelay.sh line 53'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_server_vsftpd_NKdelay.sh line 53'
Tue Nov 21 04:03:07 2023 - ERROR - oe_test_server_vsftpd_NKdelay.sh line 53
+ '[' 0 -eq 1 ']'
+ return 0
+ SSH_CMD 'tc qdisc del dev 1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms root netem loss 20%' 192.168.114.7 'openEuler12#$' root
+ cmd='tc qdisc del dev 1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms root netem loss 20%'
+ remoteip=192.168.114.7
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'tc qdisc del dev 1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms root netem loss 20%' -i 192.168.114.7 -u root -p 'openEuler12#$' -t 300 -o 22
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
Tue Nov 21 04:03:10 2023 - ERROR - connection to 192.168.114.7 failed.
+ ret=101
+ test 101 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:101'
+ message='Failed in remote CMD operation:101'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:101'
Tue Nov 21 04:03:11 2023 - ERROR - Failed in remote CMD operation:101
+ return 101
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Nov 21 04:03:11 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 1
+ test 1 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Nov 21 04:03:12 2023 - ERROR - failed to execute the case.
+ exit 1
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Nov 21 04:03:12 2023 - INFO  - Start to restore the test environment.
+ SSH_CMD 'mv /etc/vsftpd/ftpusers.bak /etc/vsftpd/ftpusers;mv /etc/vsftpd/user_list.bak /etc/vsftpd/user_list;
    cd /var/ftp/pub;rm -rf download_file1.txt download_file2.txt;yum remove -y vsftpd' 192.168.114.7 'openEuler12#$' root
+ cmd='mv /etc/vsftpd/ftpusers.bak /etc/vsftpd/ftpusers;mv /etc/vsftpd/user_list.bak /etc/vsftpd/user_list;
    cd /var/ftp/pub;rm -rf download_file1.txt download_file2.txt;yum remove -y vsftpd'
+ remoteip=192.168.114.7
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'mv /etc/vsftpd/ftpusers.bak /etc/vsftpd/ftpusers;mv /etc/vsftpd/user_list.bak /etc/vsftpd/user_list;
    cd /var/ftp/pub;rm -rf download_file1.txt download_file2.txt;yum remove -y vsftpd' -i 192.168.114.7 -u root -p 'openEuler12#$' -t 300 -o 22
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
Tue Nov 21 04:03:16 2023 - ERROR - connection to 192.168.114.7 failed.
+ ret=101
+ test 101 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:101'
+ message='Failed in remote CMD operation:101'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:101'
Tue Nov 21 04:03:16 2023 - ERROR - Failed in remote CMD operation:101
+ return 101
+ rm -rf 'download_file[1-2].txt' log
+ DNF_REMOVE ftp
+ node=ftp
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmp_mte4l2x ]]
+ '[' 0 -ne 0 ']'
+ '[' ftp == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node ftp --pkgs '' --tempfile /tmp/tmp_mte4l2x
usage: rpm_manage.py install|remove [-h] [--node NODE] [--pkgs PKG] [--tempfile TEPMFILE]
rpm_manage.py: error: argument --node: invalid int value: 'ftp'
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Nov 21 04:03:19 2023 - INFO  - End to restore the test environment.
