+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Wed Nov 22 05:00:26 2023 - INFO  - Start to prepare the test environment.
+ mkdir /tmp/pigz /tmp/pigz/pigz01
+ touch /tmp/pigz/1.txt /tmp/pigz/pigz01/1.txt
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Wed Nov 22 05:00:27 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ pigz -z /tmp/pigz/1.txt
oe_test_pigz_01.sh: line 30: pigz: command not found
+ test -e /tmp/pigz/1.txt.zz
+ CHECK_RESULT 1 0 0 'pigz -z command execution failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='pigz -z command execution failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'pigz -z command execution failure'
+ LOG_ERROR 'pigz -z command execution failure'
+ message='pigz -z command execution failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'pigz -z command execution failure'
Wed Nov 22 05:00:28 2023 - ERROR - pigz -z command execution failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pigz_01.sh line 32'
+ message='oe_test_pigz_01.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pigz_01.sh line 32'
Wed Nov 22 05:00:28 2023 - ERROR - oe_test_pigz_01.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ pigz -d /tmp/pigz/1.txt.zz
oe_test_pigz_01.sh: line 33: pigz: command not found
+ test -e /tmp/pigz/1.txt
+ CHECK_RESULT 0 0 0 'pigz -d command execution failure'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='pigz -d command execution failure'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pigz -k /tmp/pigz/1.txt
oe_test_pigz_01.sh: line 36: pigz: command not found
+ test -e /tmp/pigz/1.txt
+ test -e /tmp/pigz/1.txt.gz
+ CHECK_RESULT 1 0 0 'pigz -k command execution failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='pigz -k command execution failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'pigz -k command execution failure'
+ LOG_ERROR 'pigz -k command execution failure'
+ message='pigz -k command execution failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'pigz -k command execution failure'
Wed Nov 22 05:00:29 2023 - ERROR - pigz -k command execution failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pigz_01.sh line 38'
+ message='oe_test_pigz_01.sh line 38'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pigz_01.sh line 38'
Wed Nov 22 05:00:29 2023 - ERROR - oe_test_pigz_01.sh line 38
+ '[' 0 -eq 1 ']'
+ return 0
+ pigz -f /tmp/pigz/1.txt
oe_test_pigz_01.sh: line 39: pigz: command not found
+ CHECK_RESULT 127 0 0 'pigz -f command execution failure'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='pigz -f command execution failure'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'pigz -f command execution failure'
+ LOG_ERROR 'pigz -f command execution failure'
+ message='pigz -f command execution failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'pigz -f command execution failure'
Wed Nov 22 05:00:30 2023 - ERROR - pigz -f command execution failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pigz_01.sh line 40'
+ message='oe_test_pigz_01.sh line 40'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pigz_01.sh line 40'
Wed Nov 22 05:00:30 2023 - ERROR - oe_test_pigz_01.sh line 40
+ '[' 0 -eq 1 ']'
+ return 0
+ pigz -r /tmp/pigz/pigz01/1.txt
oe_test_pigz_01.sh: line 41: pigz: command not found
+ test -e /tmp/pigz/pigz01/1.txt.gz
+ CHECK_RESULT 1 0 0 'pigz -r command execution failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='pigz -r command execution failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'pigz -r command execution failure'
+ LOG_ERROR 'pigz -r command execution failure'
+ message='pigz -r command execution failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'pigz -r command execution failure'
Wed Nov 22 05:00:30 2023 - ERROR - pigz -r command execution failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pigz_01.sh line 43'
+ message='oe_test_pigz_01.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pigz_01.sh line 43'
Wed Nov 22 05:00:31 2023 - ERROR - oe_test_pigz_01.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ CASE_RESULT 0
+ case_re=0
+ test -z 4
+ test 4 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Nov 22 05:00:31 2023 - ERROR - failed to execute the case.
+ exit 4
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Wed Nov 22 05:00:32 2023 - INFO  - Start to restore the test environment.
+ rm -rf /tmp/pigz
+ LOG_INFO 'Finish restoring the test environment.'
+ message='Finish restoring the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish restoring the test environment.'
Wed Nov 22 05:00:32 2023 - INFO  - Finish restoring the test environment.
