+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n '' ']'
+ trap POST_TEST_DEFAULT EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Tue Nov 21 09:27:01 2023 - INFO  - Start environmental preparation.
+ grep '^SyslogFacility AUTH' /etc/ssh/sshd_config
SyslogFacility AUTHPRIV
+ CHECK_RESULT 0 0 0 'SyslogFacility is not AUTH'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='SyslogFacility is not AUTH'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep '^LogLevel VERBOSE' /etc/ssh/sshd_config
+ CHECK_RESULT 1 0 0 'LogLevel is not VERBOSE'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='LogLevel is not VERBOSE'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'LogLevel is not VERBOSE'
+ LOG_ERROR 'LogLevel is not VERBOSE'
+ message='LogLevel is not VERBOSE'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'LogLevel is not VERBOSE'
Tue Nov 21 09:27:01 2023 - ERROR - LogLevel is not VERBOSE
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ssh_system_reinforcement.sh line 27'
+ message='oe_test_ssh_system_reinforcement.sh line 27'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ssh_system_reinforcement.sh line 27'
Tue Nov 21 09:27:02 2023 - ERROR - oe_test_ssh_system_reinforcement.sh line 27
+ '[' 0 -eq 1 ']'
+ return 0
+ grep '^X11Forwarding no' /etc/ssh/sshd_config
+ CHECK_RESULT 1 0 0 'X11Forwarding is not no'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='X11Forwarding is not no'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'X11Forwarding is not no'
+ LOG_ERROR 'X11Forwarding is not no'
+ message='X11Forwarding is not no'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'X11Forwarding is not no'
Tue Nov 21 09:27:02 2023 - ERROR - X11Forwarding is not no
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ssh_system_reinforcement.sh line 29'
+ message='oe_test_ssh_system_reinforcement.sh line 29'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ssh_system_reinforcement.sh line 29'
Tue Nov 21 09:27:03 2023 - ERROR - oe_test_ssh_system_reinforcement.sh line 29
+ '[' 0 -eq 1 ']'
+ return 0
+ grep '^IgnoreRhosts yes' /etc/ssh/sshd_config
+ CHECK_RESULT 1 0 0 'IgnoreRhosts is not yes'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='IgnoreRhosts is not yes'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'IgnoreRhosts is not yes'
+ LOG_ERROR 'IgnoreRhosts is not yes'
+ message='IgnoreRhosts is not yes'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'IgnoreRhosts is not yes'
Tue Nov 21 09:27:03 2023 - ERROR - IgnoreRhosts is not yes
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ssh_system_reinforcement.sh line 31'
+ message='oe_test_ssh_system_reinforcement.sh line 31'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ssh_system_reinforcement.sh line 31'
Tue Nov 21 09:27:04 2023 - ERROR - oe_test_ssh_system_reinforcement.sh line 31
+ '[' 0 -eq 1 ']'
+ return 0
+ grep '^Subsystem sftp /usr/libexec/openssh/sftp-server -l INFO -f AUTH' /etc/ssh/sshd_config
+ CHECK_RESULT 1 0 0 'grep '\''Subsystem sftp /usr/libexec/openssh/sftp-server -l INFO -f AUTH'\'' failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='grep '\''Subsystem sftp /usr/libexec/openssh/sftp-server -l INFO -f AUTH'\'' failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'grep '\''Subsystem sftp /usr/libexec/openssh/sftp-server -l INFO -f AUTH'\'' failed'
+ LOG_ERROR 'grep '\''Subsystem sftp /usr/libexec/openssh/sftp-server -l INFO -f AUTH'\'' failed'
+ message='grep '\''Subsystem sftp /usr/libexec/openssh/sftp-server -l INFO -f AUTH'\'' failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'grep '\''Subsystem sftp /usr/libexec/openssh/sftp-server -l INFO -f AUTH'\'' failed'
Tue Nov 21 09:27:04 2023 - ERROR - grep 'Subsystem sftp /usr/libexec/openssh/sftp-server -l INFO -f AUTH' failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ssh_system_reinforcement.sh line 33'
+ message='oe_test_ssh_system_reinforcement.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ssh_system_reinforcement.sh line 33'
Tue Nov 21 09:27:04 2023 - ERROR - oe_test_ssh_system_reinforcement.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ grep '^HostbasedAuthentication no' /etc/ssh/sshd_config
+ CHECK_RESULT 1 0 0 'HostbasedAuthentication is not no'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='HostbasedAuthentication is not no'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'HostbasedAuthentication is not no'
+ LOG_ERROR 'HostbasedAuthentication is not no'
+ message='HostbasedAuthentication is not no'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'HostbasedAuthentication is not no'
Tue Nov 21 09:27:05 2023 - ERROR - HostbasedAuthentication is not no
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ssh_system_reinforcement.sh line 35'
+ message='oe_test_ssh_system_reinforcement.sh line 35'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ssh_system_reinforcement.sh line 35'
Tue Nov 21 09:27:05 2023 - ERROR - oe_test_ssh_system_reinforcement.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
+ grep '^Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com' /etc/ssh/sshd_config
+ CHECK_RESULT 1 0 0 'grep '\''Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com'\'' failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='grep '\''Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com'\'' failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'grep '\''Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com'\'' failed'
+ LOG_ERROR 'grep '\''Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com'\'' failed'
+ message='grep '\''Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com'\'' failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'grep '\''Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com'\'' failed'
Tue Nov 21 09:27:06 2023 - ERROR - grep 'Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com' failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ssh_system_reinforcement.sh line 37'
+ message='oe_test_ssh_system_reinforcement.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ssh_system_reinforcement.sh line 37'
Tue Nov 21 09:27:06 2023 - ERROR - oe_test_ssh_system_reinforcement.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ grep '^ClientAliveCountMax 0' /etc/ssh/sshd_config
+ CHECK_RESULT 1 0 0 'ClientAliveCountMax is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ClientAliveCountMax is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ClientAliveCountMax is not 0'
+ LOG_ERROR 'ClientAliveCountMax is not 0'
+ message='ClientAliveCountMax is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ClientAliveCountMax is not 0'
Tue Nov 21 09:27:07 2023 - ERROR - ClientAliveCountMax is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ssh_system_reinforcement.sh line 39'
+ message='oe_test_ssh_system_reinforcement.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ssh_system_reinforcement.sh line 39'
Tue Nov 21 09:27:07 2023 - ERROR - oe_test_ssh_system_reinforcement.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
+ grep '^MACs hmac-sha2-512,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-256-etm@openssh.com' /etc/ssh/sshd_config
+ CHECK_RESULT 1 0 0 'grep '\''MACs hmac-sha2-512,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-256-etm@openssh.com'\'' failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='grep '\''MACs hmac-sha2-512,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-256-etm@openssh.com'\'' failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'grep '\''MACs hmac-sha2-512,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-256-etm@openssh.com'\'' failed'
+ LOG_ERROR 'grep '\''MACs hmac-sha2-512,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-256-etm@openssh.com'\'' failed'
+ message='grep '\''MACs hmac-sha2-512,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-256-etm@openssh.com'\'' failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'grep '\''MACs hmac-sha2-512,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-256-etm@openssh.com'\'' failed'
Tue Nov 21 09:27:08 2023 - ERROR - grep 'MACs hmac-sha2-512,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-256-etm@openssh.com' failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ssh_system_reinforcement.sh line 41'
+ message='oe_test_ssh_system_reinforcement.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ssh_system_reinforcement.sh line 41'
Tue Nov 21 09:27:08 2023 - ERROR - oe_test_ssh_system_reinforcement.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ grep '^AllowTcpForwarding no' /etc/ssh/sshd_config
+ CHECK_RESULT 1 0 0 'AllowTcpForwarding is not no'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='AllowTcpForwarding is not no'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'AllowTcpForwarding is not no'
+ LOG_ERROR 'AllowTcpForwarding is not no'
+ message='AllowTcpForwarding is not no'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'AllowTcpForwarding is not no'
Tue Nov 21 09:27:08 2023 - ERROR - AllowTcpForwarding is not no
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ssh_system_reinforcement.sh line 43'
+ message='oe_test_ssh_system_reinforcement.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ssh_system_reinforcement.sh line 43'
Tue Nov 21 09:27:09 2023 - ERROR - oe_test_ssh_system_reinforcement.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ grep '^Subsystem sftp' /etc/ssh/sshd_config
+ CHECK_RESULT 1 0 0 'Subsystem is not sftp'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Subsystem is not sftp'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Subsystem is not sftp'
+ LOG_ERROR 'Subsystem is not sftp'
+ message='Subsystem is not sftp'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Subsystem is not sftp'
Tue Nov 21 09:27:09 2023 - ERROR - Subsystem is not sftp
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ssh_system_reinforcement.sh line 45'
+ message='oe_test_ssh_system_reinforcement.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ssh_system_reinforcement.sh line 45'
Tue Nov 21 09:27:10 2023 - ERROR - oe_test_ssh_system_reinforcement.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ grep '^GatewayPorts no' /etc/ssh/sshd_config
+ CHECK_RESULT 1 0 0 'GatewayPorts is not no'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='GatewayPorts is not no'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'GatewayPorts is not no'
+ LOG_ERROR 'GatewayPorts is not no'
+ message='GatewayPorts is not no'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'GatewayPorts is not no'
Tue Nov 21 09:27:10 2023 - ERROR - GatewayPorts is not no
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ssh_system_reinforcement.sh line 47'
+ message='oe_test_ssh_system_reinforcement.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ssh_system_reinforcement.sh line 47'
Tue Nov 21 09:27:11 2023 - ERROR - oe_test_ssh_system_reinforcement.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ grep '^PermitTunnel no' /etc/ssh/sshd_config
+ CHECK_RESULT 1 0 0 'PermitTunnel is not no'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='PermitTunnel is not no'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'PermitTunnel is not no'
+ LOG_ERROR 'PermitTunnel is not no'
+ message='PermitTunnel is not no'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'PermitTunnel is not no'
Tue Nov 21 09:27:11 2023 - ERROR - PermitTunnel is not no
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ssh_system_reinforcement.sh line 49'
+ message='oe_test_ssh_system_reinforcement.sh line 49'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ssh_system_reinforcement.sh line 49'
Tue Nov 21 09:27:11 2023 - ERROR - oe_test_ssh_system_reinforcement.sh line 49
+ '[' 0 -eq 1 ']'
+ return 0
+ grep '^KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group-exchange-sha256' /etc/ssh/sshd_config
+ grep '^KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256' /etc/ssh/sshd_config
+ CHECK_RESULT 1 0 0 'grep KexAlgorithms failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='grep KexAlgorithms failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'grep KexAlgorithms failed'
+ LOG_ERROR 'grep KexAlgorithms failed'
+ message='grep KexAlgorithms failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'grep KexAlgorithms failed'
Tue Nov 21 09:27:12 2023 - ERROR - grep KexAlgorithms failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ssh_system_reinforcement.sh line 51'
+ message='oe_test_ssh_system_reinforcement.sh line 51'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ssh_system_reinforcement.sh line 51'
Tue Nov 21 09:27:12 2023 - ERROR - oe_test_ssh_system_reinforcement.sh line 51
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Tue Nov 21 09:27:13 2023 - INFO  - End of environmental preparation!
+ CASE_RESULT 0
+ case_re=0
+ test -z 13
+ test 13 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Nov 21 09:27:13 2023 - ERROR - failed to execute the case.
+ exit 13
+ POST_TEST_DEFAULT
+ LOG_INFO 'oe_test_ssh_system_reinforcement.sh post_test'
+ message='oe_test_ssh_system_reinforcement.sh post_test'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'oe_test_ssh_system_reinforcement.sh post_test'
Tue Nov 21 09:27:14 2023 - INFO  - oe_test_ssh_system_reinforcement.sh post_test
